/* tslint:disable */
/* eslint-disable */
/**
 * ABC30
 * ABC30
 *
 * The version of the OpenAPI document: 1.0
 * Contact: zsolt.nagy@ingenimind.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExampleDTO
 */
export interface ExampleDTO {
    /**
     * The ID
     * @type {string}
     * @memberof ExampleDTO
     */
    id?: string;
    /**
     * The language of the example
     * @type {string}
     * @memberof ExampleDTO
     */
    language?: string;
    /**
     * The example order
     * @type {number}
     * @memberof ExampleDTO
     */
    sequence?: number;
    /**
     * The example
     * @type {string}
     * @memberof ExampleDTO
     */
    value?: string;
    /**
     * The word ID
     * @type {string}
     * @memberof ExampleDTO
     */
    wordId?: string;
}

/**
 * Check if a given object implements the ExampleDTO interface.
 */
export function instanceOfExampleDTO(value: object): boolean {
    return true;
}

export function ExampleDTOFromJSON(json: any): ExampleDTO {
    return ExampleDTOFromJSONTyped(json, false);
}

export function ExampleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExampleDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'language': json['language'] == null ? undefined : json['language'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'value': json['value'] == null ? undefined : json['value'],
        'wordId': json['wordId'] == null ? undefined : json['wordId'],
    };
}

export function ExampleDTOToJSON(value?: ExampleDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'language': value['language'],
        'sequence': value['sequence'],
        'value': value['value'],
        'wordId': value['wordId'],
    };
}

