/* tslint:disable */
/* eslint-disable */
/**
 * ABC30
 * ABC30
 *
 * The version of the OpenAPI document: 1.0
 * Contact: zsolt.nagy@ingenimind.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheckDTO
 */
export interface HealthCheckDTO {
    /**
     * The API version
     * @type {Array<string>}
     * @memberof HealthCheckDTO
     */
    apiVersion?: Array<string>;
    /**
     * Docker build version
     * @type {string}
     * @memberof HealthCheckDTO
     */
    buildVersion?: string;
    /**
     * The service name
     * @type {string}
     * @memberof HealthCheckDTO
     */
    service?: string;
    /**
     * The service status
     * @type {string}
     * @memberof HealthCheckDTO
     */
    status?: string;
}

/**
 * Check if a given object implements the HealthCheckDTO interface.
 */
export function instanceOfHealthCheckDTO(value: object): boolean {
    return true;
}

export function HealthCheckDTOFromJSON(json: any): HealthCheckDTO {
    return HealthCheckDTOFromJSONTyped(json, false);
}

export function HealthCheckDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'buildVersion': json['buildVersion'] == null ? undefined : json['buildVersion'],
        'service': json['service'] == null ? undefined : json['service'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HealthCheckDTOToJSON(value?: HealthCheckDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'apiVersion': value['apiVersion'],
        'buildVersion': value['buildVersion'],
        'service': value['service'],
        'status': value['status'],
    };
}

