/* tslint:disable */
/* eslint-disable */
/**
 * ABC30
 * ABC30
 *
 * The version of the OpenAPI document: 1.0
 * Contact: zsolt.nagy@ingenimind.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LetterDTO
 */
export interface LetterDTO {
    /**
     * The ID
     * @type {string}
     * @memberof LetterDTO
     */
    id?: string;
    /**
     * The language
     * @type {string}
     * @memberof LetterDTO
     */
    language?: string;
    /**
     * The letter order
     * @type {number}
     * @memberof LetterDTO
     */
    sequence?: number;
    /**
     * The letter
     * @type {string}
     * @memberof LetterDTO
     */
    value?: string;
}

/**
 * Check if a given object implements the LetterDTO interface.
 */
export function instanceOfLetterDTO(value: object): boolean {
    return true;
}

export function LetterDTOFromJSON(json: any): LetterDTO {
    return LetterDTOFromJSONTyped(json, false);
}

export function LetterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LetterDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'language': json['language'] == null ? undefined : json['language'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function LetterDTOToJSON(value?: LetterDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'language': value['language'],
        'sequence': value['sequence'],
        'value': value['value'],
    };
}

