/* tslint:disable */
/* eslint-disable */
/**
 * ABC30
 * ABC30
 *
 * The version of the OpenAPI document: 1.0
 * Contact: zsolt.nagy@ingenimind.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ModelGrammaticalExpressionType = {
    UndefinedGrammaticalExpressionType: 'Undefined',
    IdiomType: 'Idiom',
    ProverbType: 'Proverb'
} as const;
export type ModelGrammaticalExpressionType = typeof ModelGrammaticalExpressionType[keyof typeof ModelGrammaticalExpressionType];


export function ModelGrammaticalExpressionTypeFromJSON(json: any): ModelGrammaticalExpressionType {
    return ModelGrammaticalExpressionTypeFromJSONTyped(json, false);
}

export function ModelGrammaticalExpressionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelGrammaticalExpressionType {
    return json as ModelGrammaticalExpressionType;
}

export function ModelGrammaticalExpressionTypeToJSON(value?: ModelGrammaticalExpressionType | null): any {
    return value as any;
}

