/* tslint:disable */
/* eslint-disable */
/**
 * ABC30
 * ABC30
 *
 * The version of the OpenAPI document: 1.0
 * Contact: zsolt.nagy@ingenimind.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranslationDTO
 */
export interface TranslationDTO {
    /**
     * The ID
     * @type {string}
     * @memberof TranslationDTO
     */
    id?: string;
    /**
     * The translation order
     * @type {number}
     * @memberof TranslationDTO
     */
    sequence?: number;
    /**
     * The translated word relation type
     * @type {number}
     * @memberof TranslationDTO
     */
    type?: number;
    /**
     * The translated word
     * @type {string}
     * @memberof TranslationDTO
     */
    value?: string;
    /**
     * The word ID
     * @type {string}
     * @memberof TranslationDTO
     */
    wordId?: string;
}

/**
 * Check if a given object implements the TranslationDTO interface.
 */
export function instanceOfTranslationDTO(value: object): boolean {
    return true;
}

export function TranslationDTOFromJSON(json: any): TranslationDTO {
    return TranslationDTOFromJSONTyped(json, false);
}

export function TranslationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
        'wordId': json['wordId'] == null ? undefined : json['wordId'],
    };
}

export function TranslationDTOToJSON(value?: TranslationDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'sequence': value['sequence'],
        'type': value['type'],
        'value': value['value'],
        'wordId': value['wordId'],
    };
}

