/* tslint:disable */
/* eslint-disable */
/**
 * ABC30
 * ABC30
 *
 * The version of the OpenAPI document: 1.0
 * Contact: zsolt.nagy@ingenimind.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordFormDTO
 */
export interface WordFormDTO {
    /**
     * The ID
     * @type {string}
     * @memberof WordFormDTO
     */
    id?: string;
    /**
     * The form order
     * @type {number}
     * @memberof WordFormDTO
     */
    sequence?: number;
    /**
     * The form type
     * @type {string}
     * @memberof WordFormDTO
     */
    type?: string;
    /**
     * The word form
     * @type {string}
     * @memberof WordFormDTO
     */
    value?: string;
    /**
     * The word ID
     * @type {string}
     * @memberof WordFormDTO
     */
    wordId?: string;
}

/**
 * Check if a given object implements the WordFormDTO interface.
 */
export function instanceOfWordFormDTO(value: object): boolean {
    return true;
}

export function WordFormDTOFromJSON(json: any): WordFormDTO {
    return WordFormDTOFromJSONTyped(json, false);
}

export function WordFormDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordFormDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
        'wordId': json['wordId'] == null ? undefined : json['wordId'],
    };
}

export function WordFormDTOToJSON(value?: WordFormDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'sequence': value['sequence'],
        'type': value['type'],
        'value': value['value'],
        'wordId': value['wordId'],
    };
}

