/* tslint:disable */
/* eslint-disable */
/**
 * ABC30
 * ABC30
 *
 * The version of the OpenAPI document: 1.0
 * Contact: zsolt.nagy@ingenimind.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { HealthCheckDTO } from "../models";
import { HealthCheckDTOFromJSON, HealthCheckDTOToJSON } from "../models";

/**
 *
 */
export class HealthApi extends runtime.BaseAPI {
  /**
   * Shows if the service is running or not.
   * Service health check
   */
  async getHealthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HealthCheckDTO>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/health`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      HealthCheckDTOFromJSON(jsonValue),
    );
  }

  /**
   * Shows if the service is running or not.
   * Service health check
   */
  async getHealth(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HealthCheckDTO> {
    const response = await this.getHealthRaw(initOverrides);
    return await response.value();
  }
}
