/* tslint:disable */
/* eslint-disable */
/**
 * ABC30
 * ABC30
 *
 * The version of the OpenAPI document: 1.0
 * Contact: zsolt.nagy@ingenimind.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { LetterDTO } from "../models";
import { LetterDTOFromJSON, LetterDTOToJSON } from "../models";

export interface GetLettersV1Request {
  xApiVersion?: string;
}

/**
 *
 */
export class LetterApi extends runtime.BaseAPI {
  /**
   * Gets all letter
   * Get letters
   */
  async getLettersV1Raw(
    requestParameters: GetLettersV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LetterDTO>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["xApiVersion"] != null) {
      headerParameters["x-api-version"] = String(
        requestParameters["xApiVersion"],
      );
    }

    const response = await this.request(
      {
        path: `/api/letters`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(LetterDTOFromJSON),
    );
  }

  /**
   * Gets all letter
   * Get letters
   */
  async getLettersV1(
    requestParameters: GetLettersV1Request = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LetterDTO>> {
    const response = await this.getLettersV1Raw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
